/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package athens_stock.view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author lullaby
 */
public class MenuSales extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    JFrame test;

    public MenuSales() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }
    
    public void setJFrame(JFrame f) {
        test = f;
    }

    public JFrame getJFrame() {
        return this.test;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        athensPic = new javax.swing.JLabel();
        lbStockManage = new javax.swing.JLabel();
        ldWelcome = new javax.swing.JLabel();
        btnCheckStock = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        lbSales = new javax.swing.JLabel();
        btnAddSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        athensPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/athens_stock/res/athens.jpg"))); // NOI18N

        lbStockManage.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lbStockManage.setText("Stock Management System");

        ldWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        ldWelcome.setText("Welcome to Stock Management System !");

        btnCheckStock.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        btnCheckStock.setText("Check Stock");

        btnOrder.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        btnOrder.setText("Order Item");

        btnSupplier.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        btnSupplier.setText("Supplier");

        lbSales.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        lbSales.setText("Sales");

        btnAddSupplier.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(athensPic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbStockManage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ldWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnCheckStock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lbSales))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnSupplier))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnAddSupplier)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(athensPic)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbStockManage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ldWelcome)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lbSales)
                .addGap(40, 40, 40)
                .addComponent(btnCheckStock)
                .addGap(30, 30, 30)
                .addComponent(btnSupplier)
                .addGap(30, 30, 30)
                .addComponent(btnOrder)
                .addGap(30, 30, 30)
                .addComponent(btnAddSupplier)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCheckStockAction(ActionListener action){
        btnCheckStock.addActionListener(action);
    }
    
    public void setSupplierAction(ActionListener action){
        btnSupplier.addActionListener(action);
    }
    
    public void setOrderItemAction(ActionListener action){
        btnOrder.addActionListener(action);
    }
    
    public void setAddCustomerAction(ActionListener action){
        btnAddSupplier.addActionListener(action);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckStock;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JLabel athensPic;
    private javax.swing.JLabel lbStockManage;
    private javax.swing.JLabel lbSales;
    private javax.swing.JLabel ldWelcome;
    // End of variables declaration//GEN-END:variables
}
